"""
Image Editing Module - Applies VLM-generated edit instructions to images.

Supports multiple backends:
- Qwen-Image-Edit (default): Higher quality, better text/semantic editing
- InstructPix2Pix: Faster, lower VRAM requirements

Usage:
    editor = ImageEditor(model_name="Qwen/Qwen-Image-Edit")
    edited = editor.edit(image, "Remove the background")
"""
from __future__ import annotations
import contextlib
import logging
import os
import sys

from PIL import Image

logger = logging.getLogger(__name__)


@contextlib.contextmanager
def suppress_output():
    """Context manager to suppress stdout/stderr and tqdm during model loading."""
    import tqdm

    # Save original
    old_stdout = sys.stdout
    old_stderr = sys.stderr

    # Disable tqdm globally
    original_tqdm_init = tqdm.tqdm.__init__
    def silent_tqdm_init(self, *args, **kwargs):
        kwargs['disable'] = True
        return original_tqdm_init(self, *args, **kwargs)
    tqdm.tqdm.__init__ = silent_tqdm_init

    # Redirect to devnull
    with open(os.devnull, 'w') as devnull:
        sys.stdout = devnull
        sys.stderr = devnull
        try:
            yield
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr
            tqdm.tqdm.__init__ = original_tqdm_init

# Guidance scale defaults
# Qwen-Image-Edit uses true_cfg_scale (recommended: 4.0)
# InstructPix2Pix uses image_guidance_scale + guidance_scale
_IMAGE_GUIDANCE = 1.5  # InstructPix2Pix only
_TEXT_GUIDANCE = 6.0   # true_cfg_scale for Qwen (cfg), guidance_scale for Pix2Pix
_NUM_STEPS = 28        # Inference steps for Qwen/Pix2Pix
_FLUX_STEPS = 4        # Flux2 Klein only needs 4 steps
_MAX_DIMENSION = 768   # Max image dimension


class ImageEditor:
    """
    Applies natural language edit instructions to images.

    Supports three backends:
    - Qwen/Qwen-Image-Edit: Higher quality, 20B model, requires more VRAM
    - black-forest-labs/FLUX.2-klein-9b-kv: Fast, high quality, 9B model
    - timbrooks/instruct-pix2pix: Faster, lower VRAM, good for quick iterations

    The edit instruction text is generated by the VLM (Qwen2.5-VL).
    """

    def __init__(self, model_name: str = "black-forest-labs/FLUX.2-klein-9b-kv",
                 device: str = "cuda", dtype: str = "bfloat16", use_8bit: bool = True):
        import torch
        import diffusers
        import logging as _logging
        diffusers.logging.set_verbosity_error()
        _logging.getLogger("diffusers").setLevel(_logging.ERROR)

        self.device = device
        self._model_name = model_name
        self._dtype_str = dtype
        self._use_fp8_offload = use_8bit  # Use FP8 + group offloading for memory efficiency
        self.loaded = True
        self._is_qwen = "qwen" in model_name.lower()
        self._is_flux = "flux" in model_name.lower()

        torch_dtype = getattr(torch, dtype)

        logger.debug("Loading image editor: %s (fp8_offload: %s)", model_name, self._use_fp8_offload)
        with suppress_output():
            if self._is_flux:
                # Flux2 Klein 9B KV - fast and high quality
                from diffusers import Flux2KleinKVPipeline

                self.pipe = Flux2KleinKVPipeline.from_pretrained(
                    model_name,
                    torch_dtype=torch.bfloat16,
                )

                if self._use_fp8_offload:
                    self.pipe.enable_model_cpu_offload()
                else:
                    self.pipe.to(device)
                self.pipe.set_progress_bar_config(disable=True)

            elif self._is_qwen:
                # Qwen-Image-Edit
                from diffusers import QwenImageEditPipeline

                self.pipe = QwenImageEditPipeline.from_pretrained(
                    model_name,
                    torch_dtype=torch.bfloat16,
                )

                if self._use_fp8_offload:
                    self._apply_fp8_offload()
                else:
                    self.pipe.to(device)
                    self.pipe.set_progress_bar_config(disable=True)

            else:
                # InstructPix2Pix
                from diffusers import StableDiffusionInstructPix2PixPipeline
                self.pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
                    model_name,
                    torch_dtype=torch_dtype,
                    safety_checker=None,
                ).to(device)
                self.pipe.set_progress_bar_config(disable=True)

        backend = "Flux2" if self._is_flux else ("Qwen" if self._is_qwen else "InstructPix2Pix")
        logger.debug("Image editor loaded: %s", backend)

    def _apply_fp8_offload(self):
        """Apply FP8 layerwise casting + group offloading for memory efficiency."""
        import torch
        from diffusers.hooks import apply_group_offloading

        onload_device = torch.device("cuda")
        offload_device = torch.device("cpu")

        # FP8 storage with bfloat16 compute for transformer
        self.pipe.transformer.enable_layerwise_casting(
            storage_dtype=torch.float8_e4m3fn,
            compute_dtype=torch.bfloat16,
        )

        # Group offloading for transformer (leaf level with streaming)
        self.pipe.transformer.enable_group_offload(
            onload_device=onload_device,
            offload_device=offload_device,
            offload_type="leaf_level",
            use_stream=True,
        )

        # Group offloading for text encoder (block level)
        apply_group_offloading(
            self.pipe.text_encoder,
            onload_device=onload_device,
            offload_type="block_level",
            num_blocks_per_group=2,
        )

        # Group offloading for VAE (leaf level)
        apply_group_offloading(
            self.pipe.vae,
            onload_device=onload_device,
            offload_type="leaf_level",
        )

    def offload(self):
        """Free VRAM by deleting the pipeline."""
        import torch
        import gc
        del self.pipe
        self.pipe = None
        gc.collect()
        torch.cuda.empty_cache()
        self.loaded = False

    def load_to_gpu(self):
        """Reload pipeline to GPU if it was offloaded."""
        import torch
        import diffusers
        import logging as _logging
        diffusers.logging.set_verbosity_error()
        _logging.getLogger("diffusers").setLevel(_logging.ERROR)

        if not self.loaded:
            torch_dtype = getattr(torch, self._dtype_str)
            with suppress_output():
                if self._is_flux:
                    from diffusers import Flux2KleinKVPipeline
                    self.pipe = Flux2KleinKVPipeline.from_pretrained(
                        self._model_name,
                        torch_dtype=torch.bfloat16,
                    )
                    if self._use_fp8_offload:
                        self.pipe.enable_model_cpu_offload()
                    else:
                        self.pipe.to(self.device)
                    self.pipe.set_progress_bar_config(disable=True)
                elif self._is_qwen:
                    from diffusers import QwenImageEditPipeline
                    self.pipe = QwenImageEditPipeline.from_pretrained(
                        self._model_name,
                        torch_dtype=torch.bfloat16,
                    )
                    if self._use_fp8_offload:
                        self._apply_fp8_offload()
                        # Don't call set_progress_bar_config with FP8 offload
                    else:
                        self.pipe.to(self.device)
                        self.pipe.set_progress_bar_config(disable=True)
                else:
                    from diffusers import StableDiffusionInstructPix2PixPipeline
                    self.pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
                        self._model_name,
                        torch_dtype=torch_dtype,
                        safety_checker=None,
                    ).to(self.device)
                    self.pipe.set_progress_bar_config(disable=True)
            self.loaded = True

    def edit(self, image: Image.Image, instruction: str,
             image_guidance_scale: float = _IMAGE_GUIDANCE,
             text_guidance_scale: float = _TEXT_GUIDANCE,
             num_steps: int = _NUM_STEPS,
             seed: int = 42) -> Image.Image:
        """
        Apply an edit instruction to the image.

        Args:
            image: PIL Image to edit.
            instruction: Natural language edit (e.g., "remove the cat's tail").
            image_guidance_scale: How much to preserve original image structure (InstructPix2Pix only).
            text_guidance_scale: How strongly to follow the instruction (cfg).
            num_steps: Diffusion inference steps.
            seed: Random seed for reproducibility.

        Returns:
            Edited PIL Image.
        """
        import torch

        original_size = image.size
        img = image.convert("RGB")

        # Resize preserving aspect ratio, with max dimension = _MAX_DIMENSION
        # and ensure dimensions are divisible by 8 (required by diffusion model)
        w, h = img.size
        scale = min(_MAX_DIMENSION / max(w, h), 1.0)  # don't upscale
        new_w = int(w * scale) // 8 * 8
        new_h = int(h * scale) // 8 * 8
        new_w = max(new_w, 256)  # minimum size
        new_h = max(new_h, 256)

        img = img.resize((new_w, new_h), Image.LANCZOS)

        # Append constraint to keep other parts unchanged
        full_prompt = f"{instruction}. Keep everything else unchanged."

        # Use CPU generator when using FP8 offload (model moves between CPU/GPU)
        gen_device = "cpu" if (self._is_qwen and self._use_fp8_offload) else self.device
        generator = torch.Generator(device=gen_device).manual_seed(seed)

        # Determine actual steps based on model
        actual_steps = _FLUX_STEPS if self._is_flux else num_steps
        logger.debug("Editor.edit: instruction='%s', seed=%d, size=%dx%d, steps=%d, cfg=%.1f",
                    instruction[:60], seed, new_w, new_h, actual_steps, text_guidance_scale)

        try:
            if self._is_flux:
                # Flux2 Klein 9B KV API - fast image editing (only needs 4 steps)
                with torch.inference_mode():
                    result = self.pipe(
                        prompt=full_prompt,
                        image=img,
                        num_inference_steps=actual_steps,
                        generator=generator,
                    )
            elif self._is_qwen:
                # Qwen-Image-Edit API (doesn't support strength parameter)
                with torch.inference_mode():
                    result = self.pipe(
                        image=img,
                        prompt=full_prompt,
                        generator=generator,
                        true_cfg_scale=text_guidance_scale,
                        negative_prompt=" ",
                        num_inference_steps=num_steps,
                    )
            else:
                # InstructPix2Pix API
                result = self.pipe(
                    prompt=full_prompt,
                    image=img,
                    num_inference_steps=num_steps,
                    image_guidance_scale=image_guidance_scale,
                    guidance_scale=text_guidance_scale,
                    generator=generator,
                )

            edited: Image.Image = result.images[0]
            # Resize back to original dimensions
            return edited.resize(original_size, Image.LANCZOS)

        except torch.cuda.OutOfMemoryError as e:
            logger.error("CUDA OUT OF MEMORY during image editing: %s", e)
            logger.error("Try running with fewer generations or smaller batch size")
            # Try to recover VRAM
            torch.cuda.empty_cache()
            raise
        except Exception as e:
            logger.error("Image editing failed: %s (instruction: %s)", e, instruction[:50])
            logger.error("Full traceback:", exc_info=True)
            raise
